

site_name: Python on whales
docs_dir: generated_sources
site_description: 'Python on whales docs'

nav:
  - index: index.md
  - Docker client: docker_client.md
  - Sub-commands:
    - Buildx: components/buildx.md
    - Container: components/container.md
    - Image: components/image.md
    - Network: components/network.md
    - Volume: components/volume.md
  - Docker objects:
    - Containers: docker_objects/container.md
    - Images: docker_objects/image.md
