name: Run tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run all tests
      run: |
        docker buildx build -f tests/Dockerfile .
